# Notebook for browsing the Stopping Power dataset

The Stopping Power dataset contains information about the stopping power of various materials for different types of particles. The dataset can be found at the following link: https://www-nds.iaea.org/stopping/

## Setting up the python environment for the notebook

It is recommended to use 8uv](https://docs.astral.sh/uv/) to manage the python environment and the dependencies for this notebook. The following command will create a new environment with the required dependencies:

```bash
uv venv .nds-venv --python 3.13
source .nds-venv/bin/activate
uv pip install -r requirements.txt
```

## Loading the dataset

In [1]:
%reload_ext autoreload
%autoreload 2

import pandas as pd
import plotly.express as px
import periodictable as pt

# Import only what's needed from nds_database
from nds_database import (
    DATA_PATH,
    convert_dedx,
    convert_energy,
    get_element_mass,
    harmonize_energy_units,
    is_compound,
    is_element_in_periodic_table,
)

df_original = pd.read_csv(DATA_PATH / "StoppingPower.csv")

df_original

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,dataset_last_modification,publication_year,ref_id,citation_reference,doi,comments
0,Al,27.0,Ag,s,0.159,MeV/u,4.3690,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN
1,Al,27.0,Ag,s,0.308,MeV/u,5.9630,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN
2,Al,27.0,Ag,s,0.498,MeV/u,6.8020,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN
3,Al,27.0,Ag,s,0.727,MeV/u,7.0420,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN
4,Al,27.0,Ag,s,0.981,MeV/u,7.0990,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64410,He,4.0,ZrO2,s,2221.000,keV,0.6597,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN
64411,He,4.0,ZrO2,s,2387.000,keV,0.7432,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN
64412,He,4.0,ZrO2,s,2578.000,keV,0.6077,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN
64413,He,4.0,ZrO2,s,2786.000,keV,0.6908,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN
64414,He,4.0,ZrO2,s,2919.000,keV,0.5315,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN

In [2]:
print(f"Energy units: {df_original['energy_unit'].unique()}")
print(f"Stopping power units: {df_original['stopping_unit'].unique()}")

Energy units: ['MeV/u' 'keV/u' 'keV' 'MeV']
Stopping power units: ['MeV/(mg/cm2)' 'E-15eV cm2/atom' 'eV/A' 'eV/(mg/cm2)']

In [3]:
getattr(pt, "Si")[28].density

2.321033962084814

In [4]:
is_compound("SiC")

True

In [5]:
df_harmonized = harmonize_energy_units(df_original, to="MeV/u")
df_harmonized

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,dataset_last_modification,publication_year,ref_id,citation_reference,doi,comments,ion_mass,target_mass
0,Al,27.0,Ag,s,0.159000,MeV/u,4.3690,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
1,Al,27.0,Ag,s,0.308000,MeV/u,5.9630,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
2,Al,27.0,Ag,s,0.498000,MeV/u,6.8020,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
3,Al,27.0,Ag,s,0.727000,MeV/u,7.0420,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
4,Al,27.0,Ag,s,0.981000,MeV/u,7.0990,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64410,He,4.0,ZrO2,s,0.554889,MeV/u,0.6597,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN,4.002603,164.402926
64411,He,4.0,ZrO2,s,0.596362,MeV/u,0.7432,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN,4.002603,164.402926
64412,He,4.0,ZrO2,s,0.644081,MeV/u,0.6077,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN,4.002603,164.402926
64413,He,4.0,ZrO2,s,0.696047,MeV/u,0.6908,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN,4.002603,164.402926
64414,He,4.0,ZrO2,s,0.729275,MeV/u,0.5315,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN,4.002603,164.402926

In [6]:
projectiles = list(df_original["projectile_name"].unique())
targets = list(df_original["target_name"].unique())

print(f"number of projectiles: {len(projectiles)}")
print(f"number of targets: {len(targets)}")

unique_combinations = df_original[["projectile_name", "target_name"]].drop_duplicates()
print(f"number of unique combinations: {len(unique_combinations)}")
unique_combinations

number of projectiles: 58
number of targets: 275
number of unique combinations: 1532

      projectile_name target_name
0                  Al          Ag
13                 Al          Al
24                 Al          Cu
38                 Al      Carbon
44                 Al          Au
...               ...         ...
64017              Be       Ta2O5
64099              Li       Nb2O5
64123              Li       Ta2O5
64318              Be        ZrO2
64399              He        ZrO2

[1532 rows x 2 columns]

In [7]:
from ipywidgets import interact

df_elemental_only = df_harmonized[
    df_harmonized["target_name"].apply(is_element_in_periodic_table)
]

df_elemental_only

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,dataset_last_modification,publication_year,ref_id,citation_reference,doi,comments,ion_mass,target_mass
0,Al,27.0,Ag,s,0.159000,MeV/u,4.369,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
1,Al,27.0,Ag,s,0.308000,MeV/u,5.963,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
2,Al,27.0,Ag,s,0.498000,MeV/u,6.802,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
3,Al,27.0,Ag,s,0.727000,MeV/u,7.042,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
4,Al,27.0,Ag,s,0.981000,MeV/u,7.099,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64291,He,4.0,Si,s,0.615609,MeV/u,44.310,E-15eV cm2/atom,4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,112.413112
64292,He,4.0,Si,s,0.643037,MeV/u,40.030,E-15eV cm2/atom,4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,112.413112
64293,He,4.0,Si,s,0.679608,MeV/u,41.310,E-15eV cm2/atom,4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,112.413112
64294,He,4.0,Si,s,0.706021,MeV/u,36.780,E-15eV cm2/atom,4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,112.413112
64295,He,4.0,Si,s,0.727354,MeV/u,37.030,E-15eV cm2/atom,4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,112.413112

In [ ]:
df = df_elemental_only.sort_values(["projectile_name"])
projectiles = list(df_elemental_only["projectile_name"].unique())


def filter_by_ion(ion: str):
    df_ = df.copy()

    df_ = df_[df_["projectile_name"] == ion]

    fig = px.scatter(
        df_,
        x="energy",
        y="stopping_power",
        symbol="stopping_unit",
        color="target_name",
        log_x=True,
        log_y=True,
        hover_data=["energy", "energy_unit", "stopping_unit"],
        width=1200,
        height=600,
    )
    # fig.show()
    return fig


f = interact(filter_by_ion, ion=projectiles)

interactive(children=(Dropdown(description='ion', options=('Al', 'C', 'O', 'Ag', 'Ti', 'Cu', 'Au', 'I', 'N', '…

In [9]:
df = df.sort_values(["target_name"])
targets = df["target_name"].unique()


def filter_by_target(target: str):
    df_ = df.copy()

    df_ = df_[df_["target_name"] == target]

    fig = px.scatter(
        df_,
        x="energy",
        y="stopping_power",
        color="stopping_unit",
        symbol="projectile_name",
        log_x=True,
        log_y=True,
        hover_data=["energy", "energy_unit", "stopping_unit"],
        width=1200,
        height=600,
    )

    fig.show()


selected_ion = interact(filter_by_target, target=targets)

interactive(children=(Dropdown(description='target', options=('Ag', 'Al', 'Ar', 'Au', 'B', 'Be', 'Bi', 'Br', '…

In [10]:
df_elemental_only

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,dataset_last_modification,publication_year,ref_id,citation_reference,doi,comments,ion_mass,target_mass
0,Al,27.0,Ag,s,0.159000,MeV/u,4.369,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
1,Al,27.0,Ag,s,0.308000,MeV/u,5.963,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
2,Al,27.0,Ag,s,0.498000,MeV/u,6.802,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
3,Al,27.0,Ag,s,0.727000,MeV/u,7.042,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
4,Al,27.0,Ag,s,0.981000,MeV/u,7.099,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,2910.449982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64291,He,4.0,Si,s,0.615609,MeV/u,44.310,E-15eV cm2/atom,4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,112.413112
64292,He,4.0,Si,s,0.643037,MeV/u,40.030,E-15eV cm2/atom,4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,112.413112
64293,He,4.0,Si,s,0.679608,MeV/u,41.310,E-15eV cm2/atom,4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,112.413112
64294,He,4.0,Si,s,0.706021,MeV/u,36.780,E-15eV cm2/atom,4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,112.413112
64295,He,4.0,Si,s,0.727354,MeV/u,37.030,E-15eV cm2/atom,4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,112.413112

In [11]:
ion = pt.Al
isotope = 27.0
target = pt.Ag

print(f"mass ratio: {target.mass / ion.mass}")
print(f"raw ratio: {target.mass / isotope}")

mass ratio: 3.997852101717076
raw ratio: 3.9951185185185185

In [12]:
pt.Cu.density

8.96