# Notebook for browsing the Stopping Power dataset

The Stopping Power dataset contains information about the stopping power of various materials for different types of particles. The dataset can be found at the following link: https://www-nds.iaea.org/stopping/

In [2]:
%reload_ext autoreload
%autoreload 2

import pandas as pd
import plotly.express as px
import periodictable as pt

# Import only what's needed from nds_database
from nds_dedx_database import (
    DATA_PATH,
    convert_dedx,
    convert_energy,
    get_element_mass,
    get_element_density,
    get_element_symbol,
    harmonize_energy_units,
    harmonize_dedx_units,
    is_compound,
    is_element_in_periodic_table,
)

df_original = pd.read_csv(DATA_PATH / "StoppingPower.csv")

df_original

/var/folders/_2/63g8y8g568q958hmd9yxr2mc0000gp/T/ipykernel_83355/1286559095.py:22: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_original = pd.read_csv(DATA_PATH / "StoppingPower.csv")

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,dataset_last_modification,publication_year,ref_id,citation_reference,doi,comments,facility,technique,stopping_power_converted,stopping_unit_converted
0,S,32.0,Ge,s,0.080000,MeV/u,4.02,MeV/(mg/cm2),5,72.630000,2023-11-27,2001,Nig2001,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.020000,MeV/(mg/cm2)
1,S,32.0,Ge,s,0.092500,MeV/u,4.54,MeV/(mg/cm2),5,72.630000,2023-11-27,2001,Nig2001,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.540000,MeV/(mg/cm2)
2,S,32.0,Ge,s,0.115625,MeV/u,4.88,MeV/(mg/cm2),5,72.630000,2023-11-27,2001,Nig2001,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.880000,MeV/(mg/cm2)
3,S,32.0,Ge,s,0.135313,MeV/u,5.29,MeV/(mg/cm2),5,72.630000,2023-11-27,2001,Nig2001,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,5.290000,MeV/(mg/cm2)
4,S,32.0,Ge,s,0.137187,MeV/u,5.50,MeV/(mg/cm2),5,72.630000,2023-11-27,2001,Nig2001,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,5.500000,MeV/(mg/cm2)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64607,He,4.0,SiO2,s,100.000000,keV,29.15,E-15eV cm2/atom,5,20.027667,2026-01-28,2025,SYA2025,"SungYup An et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2024.165598,NaN,"Research Center for Materials Analysis, Korea ...",X-ray reﬂectometry (XRR) and medium-energy ion...,0.876271,MeV/(mg/cm2)
64608,He,4.0,SiO2,s,73.220000,keV,25.93,E-15eV cm2/atom,5,20.027667,2026-01-28,2025,SYA2025,"SungYup An et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2024.165598,NaN,"Research Center for Materials Analysis, Korea ...",X-ray reﬂectometry (XRR) and medium-energy ion...,0.779476,MeV/(mg/cm2)
64609,He,4.0,SiO2,s,61.150000,keV,24.23,E-15eV cm2/atom,5,20.027667,2026-01-28,2025,SYA2025,"SungYup An et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2024.165598,NaN,"Research Center for Materials Analysis, Korea ...",X-ray reﬂectometry (XRR) and medium-energy ion...,0.728372,MeV/(mg/cm2)
64610,He,4.0,SiO2,s,44.770000,keV,21.55,E-15eV cm2/atom,5,20.027667,2026-01-28,2025,SYA2025,"SungYup An et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2024.165598,NaN,"Research Center for Materials Analysis, Korea ...",X-ray reﬂectometry (XRR) and medium-energy ion...,0.647809,MeV/(mg/cm2)
64611,He,4.0,SiO2,s,37.400000,keV,20.14,E-15eV cm2/atom,5,20.027667,2026-01-28,2025,SYA2025,"SungYup An et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2024.165598,NaN,"Research Center for Materials Analysis, Korea ...",X-ray reﬂectometry (XRR) and medium-energy ion...,0.605424,MeV/(mg/cm2)

In [3]:
print(f"Energy units: {df_original['energy_unit'].unique()}")
print(f"Stopping power units: {df_original['stopping_unit'].unique()}")

Energy units: ['MeV/u' 'keV/u' 'MeV' 'keV']
Stopping power units: ['MeV/(mg/cm2)' 'E-15eV cm2/atom' 'eV/A']

In [4]:
getattr(pt, "Si")[28].density

2.321033962084814

In [5]:
is_compound("SiC")

True

In [6]:
df_harmonized_energy = harmonize_energy_units(df_original, to="MeV/u")
df_harmonized_energy

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,...,ref_id,citation_reference,doi,comments,facility,technique,stopping_power_converted,stopping_unit_converted,ion_mass,target_mass
0,S,32.0,Ge,s,0.080000,MeV/u,4.02,MeV/(mg/cm2),5,72.630000,...,Nig2001,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.020000,MeV/(mg/cm2),31.972071,72.630000
1,S,32.0,Ge,s,0.092500,MeV/u,4.54,MeV/(mg/cm2),5,72.630000,...,Nig2001,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.540000,MeV/(mg/cm2),31.972071,72.630000
2,S,32.0,Ge,s,0.115625,MeV/u,4.88,MeV/(mg/cm2),5,72.630000,...,Nig2001,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.880000,MeV/(mg/cm2),31.972071,72.630000
3,S,32.0,Ge,s,0.135313,MeV/u,5.29,MeV/(mg/cm2),5,72.630000,...,Nig2001,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,5.290000,MeV/(mg/cm2),31.972071,72.630000
4,S,32.0,Ge,s,0.137187,MeV/u,5.50,MeV/(mg/cm2),5,72.630000,...,Nig2001,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,5.500000,MeV/(mg/cm2),31.972071,72.630000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64607,He,4.0,SiO2,s,0.024984,MeV/u,29.15,E-15eV cm2/atom,5,20.027667,...,SYA2025,"SungYup An et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2024.165598,NaN,"Research Center for Materials Analysis, Korea ...",X-ray reﬂectometry (XRR) and medium-energy ion...,0.876271,MeV/(mg/cm2),4.002603,20.027667
64608,He,4.0,SiO2,s,0.018293,MeV/u,25.93,E-15eV cm2/atom,5,20.027667,...,SYA2025,"SungYup An et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2024.165598,NaN,"Research Center for Materials Analysis, Korea ...",X-ray reﬂectometry (XRR) and medium-energy ion...,0.779476,MeV/(mg/cm2),4.002603,20.027667
64609,He,4.0,SiO2,s,0.015278,MeV/u,24.23,E-15eV cm2/atom,5,20.027667,...,SYA2025,"SungYup An et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2024.165598,NaN,"Research Center for Materials Analysis, Korea ...",X-ray reﬂectometry (XRR) and medium-energy ion...,0.728372,MeV/(mg/cm2),4.002603,20.027667
64610,He,4.0,SiO2,s,0.011185,MeV/u,21.55,E-15eV cm2/atom,5,20.027667,...,SYA2025,"SungYup An et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2024.165598,NaN,"Research Center for Materials Analysis, Korea ...",X-ray reﬂectometry (XRR) and medium-energy ion...,0.647809,MeV/(mg/cm2),4.002603,20.027667
64611,He,4.0,SiO2,s,0.009344,MeV/u,20.14,E-15eV cm2/atom,5,20.027667,...,SYA2025,"SungYup An et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2024.165598,NaN,"Research Center for Materials Analysis, Korea ...",X-ray reﬂectometry (XRR) and medium-energy ion...,0.605424,MeV/(mg/cm2),4.002603,20.027667

In [7]:
df_harmonized_energy["target_name"].unique()

array(['Ge', 'Si3N4', 'Kr', 'Air', 'Ti', 'N2', 'Fe', 'Carbon', 'Au', 'He',
       'Al', 'H2', 'Ag', 'Ni', 'Cu', 'Ar', 'Mylar', 'Zn', 'Ho', 'Mg',
       'Cr', 'In', 'Mo', 'Cd', 'Zr', 'Pt', 'Pd', 'W', 'Co', 'Bi', 'Re',
       'Rh', 'Ir', 'V', 'Sn', 'Mn', 'Nb', 'Kapton', 'CR-39', 'Havar',
       'Ta', 'TiN', 'Ne', 'Gd', 'Si', 'CH4', 'Nd', 'SiC', 'Lu', 'CH2',
       'LR-115', 'Celluloid', 'La', 'Tb', 'Polycarbonate', 'B', 'Dy',
       'O2', 'Al2O3', 'UF4', 'SiO2', 'Ta2O5', 'Be', 'Butane', 'CO2', 'Th',
       'NE-111', 'CF4', 'Xe', 'Pb', 'mica', 'Polyethylene',
       'Polypropylene', 'Y', 'Polyvinyl chloride', 'D2', 'Hf', 'ZrO2',
       'Formvar', 'Octafluoropropane', 'Yb', 'Nb2O5', 'GaAs', 'CH', 'Pr',
       'Er', 'Sm', 'Te', 'Ce', 'Tm', 'SF6', 'GaSb', 'TiO2', 'GaN', 'InN',
       'Decanol', 'Pentanol', 'Pentadecane', 'Tridecane', 'Toluene',
       'Undecanol', 'Diethyl ether', 'Pentane', 'Hexane', 'Octanol',
       'Methanol', 'Decene', 'Diamond', 'TaB2', 'Nonane', 'Acetone',
       'Hexene', 'TiB2', 'Heptane', 'Pentene', 'Cycloheptane', 'Octene',
       'Heptanol', 'Heptene', 'Undecane', 'Polyhydroxybutyrate', 'ZnSe',
       'Hexanol', 'TaB', 'Butanol', 'Cyclopentene', 'Se', 'Cyclopentane',
       'Dodecane', 'Decane', 'Benzene',
       'Vinylchloride vinylacetate copolymer', 'Nonanol', 'Tetradecane',
       'Cyclohexene', 'Polysulfone', 'Cyclohexane', 'Cyclooctane',
       'Glycerol', 'D2O', 'Ethanol', 'H2O', 'Octane', 'U', 'Sc', 'Ru',
       'Poly ether ether ketone', 'HfO2', 'Vitreous Carbon', 'ZnP',
       'KTiOAsO4', 'LiNbO3', 'KTaO3', 'AgGaSe2', 'KTiOPO4', 'AgGaS2',
       'SnO2', 'SrTiO3', 'Acetylene', 'AlF3', 'Polyvinyl toluene', 'Cs',
       'ZnO', 'CaF2', 'Er2O3', 'LiF', 'Polystyrene', 'ZnSiP2', 'KCl',
       'VO2', 'Rb', 'Propane', 'Li', 'Cyclopropane', 'Graphite Oxide',
       'Propylene', 'Ga', 'Sr', 'N2O', 'Pliolite S-5A', 'Cl', 'Terphenyl',
       'Br', 'Sb', 'Ca', 'Ammonia', 'Anthracene', 'NiSi', 'Graphite',
       'Hydroxyapatite', 'InP', 'Ethylene', 'NO', 'ZnTe',
       'Vinyl chloride', 'Fluoroform', 'Butene', 'SmF3', 'H2S',
       'Tissue eq', 'CdTe', 'Heptyne', 'NdF3', 'Sc2O3', 'HoF3', 'Pentyne',
       'In2O3', 'Mu metal', 'Hexyne', 'CCl4', 'Trifluoroethane',
       'Permalloy', 'GdF3', 'GaP', 'Octafluorocyclobutane', 'CClF3',
       'Ethane', 'CCl2F2', 'Butadiene', 'Styrene', 'A-150', 'CBrF3',
       'Thiophene', 'CH2Cl2', 'Trimethylamine', 'Ethylene oxide',
       'Propylene oxide', 'p-Dioxane', 'Butyraldehyde', 'Allene',
       'Dimethyl sulfide', 'SO2', 'Propylene sulfide', 'Vinyl bromide',
       'Acetaldehyde', 'Bromoethane', 'BaCl2', 'Dimethylamine', 'CS2',
       'Dimethyl ether', 'Propyne', '3-Pentanone', 'BaF2', '2-Butanone',
       'Dibromotetrafluoroethane', 'bone', 'UO2', 'Hexafluoroethane',
       'Vinyl methyl ether', 'Cyclohexadiene', 'Ethylamine',
       'Trimethylene sulfide', 'Difluoroethene', 'Cyclohexanone',
       'Carbon monoxide', 'Ethylene sulfide', 'Teflon', 'Chloroform',
       'Ethynylbenzene', 'Methylamine', 'Dimethyl sulfite', 'Butyne',
       'Ethyl iodide', 'WO3', 'CHCl2F', 'Dimethyl disulfide',
       'Propyl alcohol', 'Difluoroethane', 'Ethyl Cellulose', 'EP-PTCDI',
       'C2H3ClF2', 'C2H2ClF3', 'Eurofer97', 'Propanol', 'isooctane',
       'cis-cyclooctene', '1,2-ethanediol', '1,3-propanediol',
       '1,4-butanediol', '1,5-pentanediol', '2-methyl-1 3-butadiene',
       'bicycloheptadiene', 'Cycloheptatriene',
       'Boric-acid trimethyl ester'], dtype=object)

In [8]:
df_harmonized_dedx = harmonize_dedx_units(df_harmonized_energy, to="MeV/(mg/cm2)")
df_harmonized_dedx

Some rows were removed in harmonize_dedx_units because they contain non-elemental targets.

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,...,citation_reference,doi,comments,facility,technique,stopping_power_converted,stopping_unit_converted,ion_mass,target_mass,target_rho
0,S,32.0,Ge,s,0.080000,MeV/u,4.020000,MeV/(mg/cm2),5,72.6300,...,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.020000,MeV/(mg/cm2),31.972071,72.6300,5.344507
1,S,32.0,Ge,s,0.092500,MeV/u,4.540000,MeV/(mg/cm2),5,72.6300,...,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.540000,MeV/(mg/cm2),31.972071,72.6300,5.344507
2,S,32.0,Ge,s,0.115625,MeV/u,4.880000,MeV/(mg/cm2),5,72.6300,...,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.880000,MeV/(mg/cm2),31.972071,72.6300,5.344507
3,S,32.0,Ge,s,0.135313,MeV/u,5.290000,MeV/(mg/cm2),5,72.6300,...,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,5.290000,MeV/(mg/cm2),31.972071,72.6300,5.344507
4,S,32.0,Ge,s,0.137187,MeV/u,5.500000,MeV/(mg/cm2),5,72.6300,...,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,5.500000,MeV/(mg/cm2),31.972071,72.6300,5.344507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35666,He,4.0,Bi,s,0.864437,MeV/u,0.273766,MeV/(mg/cm2),1.8-3.8,208.9804,...,"S. Mammeri et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2025.165757,NaN,"3MV Tandetron accelerator, iThemba LABS, Cape ...",backscattering,0.273683,MeV/(mg/cm2),4.002603,208.9804,9.747000
35667,He,4.0,Bi,s,0.911907,MeV/u,0.261662,MeV/(mg/cm2),1.8-3.8,208.9804,...,"S. Mammeri et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2025.165757,NaN,"3MV Tandetron accelerator, iThemba LABS, Cape ...",backscattering,0.261584,MeV/(mg/cm2),4.002603,208.9804,9.747000
35668,He,4.0,Bi,s,0.961874,MeV/u,0.260222,MeV/(mg/cm2),1.8-3.8,208.9804,...,"S. Mammeri et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2025.165757,NaN,"3MV Tandetron accelerator, iThemba LABS, Cape ...",backscattering,0.260143,MeV/(mg/cm2),4.002603,208.9804,9.747000
35669,He,4.0,Bi,s,1.009343,MeV/u,0.251288,MeV/(mg/cm2),1.8-3.8,208.9804,...,"S. Mammeri et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2025.165757,NaN,"3MV Tandetron accelerator, iThemba LABS, Cape ...",backscattering,0.251213,MeV/(mg/cm2),4.002603,208.9804,9.747000
35670,He,4.0,Bi,s,1.056812,MeV/u,0.239473,MeV/(mg/cm2),1.8-3.8,208.9804,...,"S. Mammeri et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2025.165757,NaN,"3MV Tandetron accelerator, iThemba LABS, Cape ...",backscattering,0.239401,MeV/(mg/cm2),4.002603,208.9804,9.747000

In [9]:
projectiles = list(df_original["projectile_name"].unique())
targets = list(df_original["target_name"].unique())

print(f"number of projectiles: {len(projectiles)}")
print(f"number of targets: {len(targets)}")

unique_combinations = df_original[["projectile_name", "target_name"]].drop_duplicates()
print(f"number of unique combinations: {len(unique_combinations)}")
unique_combinations

number of projectiles: 58
number of targets: 284
number of unique combinations: 1546

      projectile_name target_name
0                   S          Ge
12                  S       Si3N4
18                  S          Kr
37                  S         Air
41                  S          Ti
...               ...         ...
64292              Co          Mo
64404               O          Mo
64418              Ti          Mo
64443              Cu          Mo
64529              He          Sb

[1546 rows x 2 columns]

In [10]:
from ipywidgets import interact

df_elemental_only = df_harmonized_dedx[
    df_harmonized_dedx["target_name"].apply(is_element_in_periodic_table)
]

all(df_elemental_only == df_harmonized_dedx)

True

In [11]:
df_elemental_only["target_name"].unique()

array(['Ge', 'Kr', 'Ti', 'Fe', 'C', 'Au', 'He', 'Al', 'Ag', 'Ni', 'Cu',
       'Ar', 'Zn', 'Ho', 'Mg', 'Cr', 'In', 'Mo', 'Cd', 'Zr', 'Pt', 'Pd',
       'W', 'Co', 'Bi', 'Re', 'Rh', 'Ir', 'V', 'Sn', 'Mn', 'Nb', 'Ta',
       'Ne', 'Gd', 'Si', 'Nd', 'Lu', 'La', 'Tb', 'B', 'Dy', 'Be', 'Th',
       'Xe', 'Pb', 'Y', 'Hf', 'Yb', 'Pr', 'Er', 'Sm', 'Te', 'Ce', 'Tm',
       'Se', 'U', 'Sc', 'Ru', 'Cs', 'Rb', 'Li', 'Ga', 'Sr', 'Cl', 'Br',
       'Sb', 'Ca'], dtype=object)

In [12]:
df = df_elemental_only.sort_values(["projectile_name"])
projectiles = list(df_elemental_only["projectile_name"].unique())


def filter_by_ion(ion: str):
    df_ = df.copy()

    df_ = df_[df_["projectile_name"] == ion]

    fig = px.scatter(
        df_,
        x="energy",
        y="stopping_power",
        symbol="stopping_unit",
        color="target_name",
        log_x=True,
        log_y=True,
        hover_data=["energy", "energy_unit", "stopping_unit"],
        width=1200,
        height=600,
    )
    # fig.show()
    return fig


f = interact(filter_by_ion, ion=projectiles)

interactive(children=(Dropdown(description='ion', options=('S', 'Sb', 'W', 'Pm', 'B', 'Ge', 'Br', 'Ca', 'Nd', …

In [13]:
df = df.sort_values(["target_name"])
targets = df["target_name"].unique()


def filter_by_target(target: str):
    df_ = df.copy()

    df_ = df_[df_["target_name"] == target]

    fig = px.scatter(
        df_,
        x="energy",
        y="stopping_power",
        color="projectile_name",
        symbol="stopping_unit",
        log_x=True,
        log_y=True,
        hover_data=["energy", "energy_unit", "stopping_unit"],
        width=1200,
        height=600,
    )

    fig.show()


selected_ion = interact(filter_by_target, target=targets)

interactive(children=(Dropdown(description='target', options=('Ag', 'Al', 'Ar', 'Au', 'B', 'Be', 'Bi', 'Br', '…

In [14]:
def filter_by_target_and_ion(ion: str, target: str):
    df_ = df.copy()

    df_ = df_[(df_["target_name"] == target) & (df_["projectile_name"] == ion)]

    fig = px.scatter(
        df_,
        x="energy",
        y="stopping_power",
        color="ref_id",
        symbol="stopping_unit",
        log_x=True,
        log_y=False,
        hover_data=["energy", "energy_unit", "stopping_unit"],
        width=1200,
        height=600,
    )

    fig.show()


selected_ion_and_target = interact(
    filter_by_target_and_ion, ion=projectiles, target=targets
)

interactive(children=(Dropdown(description='ion', options=('S', 'Sb', 'W', 'Pm', 'B', 'Ge', 'Br', 'Ca', 'Nd', …

In [15]:
df_elemental_only

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,...,citation_reference,doi,comments,facility,technique,stopping_power_converted,stopping_unit_converted,ion_mass,target_mass,target_rho
0,S,32.0,Ge,s,0.080000,MeV/u,4.020000,MeV/(mg/cm2),5,72.6300,...,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.020000,MeV/(mg/cm2),31.972071,72.6300,5.344507
1,S,32.0,Ge,s,0.092500,MeV/u,4.540000,MeV/(mg/cm2),5,72.6300,...,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.540000,MeV/(mg/cm2),31.972071,72.6300,5.344507
2,S,32.0,Ge,s,0.115625,MeV/u,4.880000,MeV/(mg/cm2),5,72.6300,...,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,4.880000,MeV/(mg/cm2),31.972071,72.6300,5.344507
3,S,32.0,Ge,s,0.135313,MeV/u,5.290000,MeV/(mg/cm2),5,72.6300,...,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,5.290000,MeV/(mg/cm2),31.972071,72.6300,5.344507
4,S,32.0,Ge,s,0.137187,MeV/u,5.500000,MeV/(mg/cm2),5,72.6300,...,"M.Nigam,J.L.Duggan,M.El Bounanani,C.Yang,S.A.D...",NaN,NaN,NaN,NaN,5.500000,MeV/(mg/cm2),31.972071,72.6300,5.344507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35666,He,4.0,Bi,s,0.864437,MeV/u,0.273766,MeV/(mg/cm2),1.8-3.8,208.9804,...,"S. Mammeri et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2025.165757,NaN,"3MV Tandetron accelerator, iThemba LABS, Cape ...",backscattering,0.273683,MeV/(mg/cm2),4.002603,208.9804,9.747000
35667,He,4.0,Bi,s,0.911907,MeV/u,0.261662,MeV/(mg/cm2),1.8-3.8,208.9804,...,"S. Mammeri et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2025.165757,NaN,"3MV Tandetron accelerator, iThemba LABS, Cape ...",backscattering,0.261584,MeV/(mg/cm2),4.002603,208.9804,9.747000
35668,He,4.0,Bi,s,0.961874,MeV/u,0.260222,MeV/(mg/cm2),1.8-3.8,208.9804,...,"S. Mammeri et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2025.165757,NaN,"3MV Tandetron accelerator, iThemba LABS, Cape ...",backscattering,0.260143,MeV/(mg/cm2),4.002603,208.9804,9.747000
35669,He,4.0,Bi,s,1.009343,MeV/u,0.251288,MeV/(mg/cm2),1.8-3.8,208.9804,...,"S. Mammeri et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2025.165757,NaN,"3MV Tandetron accelerator, iThemba LABS, Cape ...",backscattering,0.251213,MeV/(mg/cm2),4.002603,208.9804,9.747000
35670,He,4.0,Bi,s,1.056812,MeV/u,0.239473,MeV/(mg/cm2),1.8-3.8,208.9804,...,"S. Mammeri et al, Nuclear Instruments and Meth...",10.1016/j.nimb.2025.165757,NaN,"3MV Tandetron accelerator, iThemba LABS, Cape ...",backscattering,0.239401,MeV/(mg/cm2),4.002603,208.9804,9.747000

In [16]:
# check density values as sanity check
density = df_elemental_only["target_name"].apply(get_element_density)
tabulated_density = df_elemental_only["target_rho"]

px.scatter(
    x=tabulated_density,
    y=density / tabulated_density,
    labels={"x": "tabulated density", "y": "density ratio"},
)