# Notebook for browsing the Stopping Power dataset

The Stopping Power dataset contains information about the stopping power of various materials for different types of particles. The dataset can be found at the following link: https://www-nds.iaea.org/stopping/

## Setting up the python environment for the notebook

It is recommended to use 8uv](https://docs.astral.sh/uv/) to manage the python environment and the dependencies for this notebook. The following command will create a new environment with the required dependencies:

```bash
uv venv .nds-venv --python 3.13
source .nds-venv/bin/activate
uv pip install -r requirements.txt
```

## Loading the dataset

In [53]:
%reload_ext autoreload
%autoreload 2

import pandas as pd
import plotly.express as px
import periodictable as pt

# Import only what's needed from nds_database
from nds_database import (
    DATA_PATH,
    convert_dedx,
    convert_energy,
    get_element_mass,
    get_element_density,
    get_element_symbol,
    harmonize_energy_units,
    harmonize_dedx_units,
    is_compound,
    is_element_in_periodic_table,
)

df_original = pd.read_csv(DATA_PATH / "StoppingPower.csv")

df_original

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,dataset_last_modification,publication_year,ref_id,citation_reference,doi,comments
0,Al,27.0,Ag,s,0.159,MeV/u,4.3690,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN
1,Al,27.0,Ag,s,0.308,MeV/u,5.9630,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN
2,Al,27.0,Ag,s,0.498,MeV/u,6.8020,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN
3,Al,27.0,Ag,s,0.727,MeV/u,7.0420,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN
4,Al,27.0,Ag,s,0.981,MeV/u,7.0990,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64410,He,4.0,ZrO2,s,2221.000,keV,0.6597,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN
64411,He,4.0,ZrO2,s,2387.000,keV,0.7432,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN
64412,He,4.0,ZrO2,s,2578.000,keV,0.6077,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN
64413,He,4.0,ZrO2,s,2786.000,keV,0.6908,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN
64414,He,4.0,ZrO2,s,2919.000,keV,0.5315,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN

In [38]:
print(f"Energy units: {df_original['energy_unit'].unique()}")
print(f"Stopping power units: {df_original['stopping_unit'].unique()}")

Energy units: ['MeV/u' 'keV/u' 'keV' 'MeV']
Stopping power units: ['MeV/(mg/cm2)' 'E-15eV cm2/atom' 'eV/A' 'eV/(mg/cm2)']

In [39]:
getattr(pt, "Si")[28].density

2.321033962084814

In [40]:
is_compound("SiC")

True

In [41]:
df_harmonized_energy = harmonize_energy_units(df_original, to="MeV/u")
df_harmonized_energy

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,dataset_last_modification,publication_year,ref_id,citation_reference,doi,comments,ion_mass,target_mass
0,Al,27.0,Ag,s,0.159000,MeV/u,4.3690,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682
1,Al,27.0,Ag,s,0.308000,MeV/u,5.9630,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682
2,Al,27.0,Ag,s,0.498000,MeV/u,6.8020,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682
3,Al,27.0,Ag,s,0.727000,MeV/u,7.0420,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682
4,Al,27.0,Ag,s,0.981000,MeV/u,7.0990,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64410,He,4.0,ZrO2,s,0.554889,MeV/u,0.6597,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN,4.002603,41.0740
64411,He,4.0,ZrO2,s,0.596362,MeV/u,0.7432,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN,4.002603,41.0740
64412,He,4.0,ZrO2,s,0.644081,MeV/u,0.6077,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN,4.002603,41.0740
64413,He,4.0,ZrO2,s,0.696047,MeV/u,0.6908,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN,4.002603,41.0740
64414,He,4.0,ZrO2,s,0.729275,MeV/u,0.5315,MeV/(mg/cm2),4,41.0740,2023-11-27,2009,ZW2009,"Y.Zhang,W.J.Weber Nucl.Instrum.Methods Phys. R...",10.1016/j.nimb.2009.01.104,NaN,4.002603,41.0740

In [42]:
df_harmonized_energy["target_name"].unique()

array(['Ag', 'Al', 'Cu', 'Carbon', 'Au', 'Ta', 'Si', 'D2O', 'InP', 'GaN',
       'LR-115', 'Polycarbonate', 'Polypropylene', 'Mylar', 'H2O',
       'Ethanol', 'Methanol', 'Propyl alcohol', 'CH2Cl2', 'CCl4',
       'Chloroform', 'O2', 'Y', 'Havar', 'Nb', 'Co', 'Sn', 'V', 'Mg',
       'Fe', 'Ni', 'Ar', 'He', 'Air', 'H2', 'Pt', 'Be', 'Sc', 'Cr', 'Ti',
       'Mn', 'Ca', 'Zn', 'Zr', 'Gd', 'Xe', 'Kr', 'CO2', 'N2', 'Ne', 'Te',
       'Se', 'CH2', 'Polyvinyl chloride', 'W', 'Ge', 'Bi', 'Sb', 'Hf',
       'Mo', 'Re', 'Pd', 'GaAs', 'Al2O3', 'SiO2', 'ZrO2', 'CH4', 'Cl',
       'Br', 'Acetylene', 'Propane', 'Propylene', 'Ethylene', 'Octane',
       'Butene', 'Nonane', 'Heptyne', 'Decane', 'Pentyne', 'Hexyne',
       'Butane', 'Pentane', 'Hexane', 'Ethane', 'Butadiene', 'Heptane',
       'InN', 'LiNbO3', 'TiO2', 'Si3N4', 'Vitreous Carbon', 'Diamond',
       'Graphite', 'Pb', 'CaF2', 'LiF', 'Li', 'Polystyrene', 'HfO2', 'U',
       'Formvar', 'Ir', 'D2', 'CF4', 'Octafluoropropane',
       'Ethyl Cellulose', 'ZnTe', 'ZnO', 'p-Dioxane', 'Cyclooctane',
       'Benzene', 'Toluene', 'Cyclohexane', 'Cyclohexene', 'Cyclopentane',
       'Cyclohexadiene', 'Cyclohexanone', 'Ethynylbenzene',
       'Cyclopentene', 'UF4', 'Ammonia', 'Cyclopropane',
       'Carbon monoxide', 'N2O', 'Kapton', 'Dimethyl ether',
       'Diethyl ether', 'TiN', 'In', 'Er2O3', 'Sc2O3', 'Ethylene oxide',
       'Propylene oxide', 'Acetaldehyde', 'Vinyl methyl ether',
       'Butyraldehyde', 'Acetone', '3-Pentanone', '2-Butanone', 'SrTiO3',
       'Polyethylene', 'SF6', 'Rb', 'Sr', 'Nb2O5', 'Ta2O5', 'Tissue eq',
       'ZnP', 'NE-111', 'Sm', 'Yb', 'Ho', 'Cd', 'Rh', 'Th', 'Ru', 'Er',
       'CH', 'GaSb', 'Styrene', 'Polyhydroxybutyrate', 'Lu', 'A-150',
       'SiC', 'Polyvinyl toluene', 'Terphenyl', 'Anthracene', 'ZnSiP2',
       'Ga', 'GaP', 'In2O3', 'B', 'Pr', 'Ce', 'La', 'Dy', 'Cs', 'Tb',
       'Nd', 'mica', 'Decanol', 'Pentanol', 'Pentadecane', 'Tridecane',
       'Undecanol', 'Octanol', 'Decene', 'Hexene', '1-Propanol',
       'Pentene', 'Cycloheptane', 'Octene', 'Heptanol', 'Heptene',
       'Undecane', 'Hexanol', 'Butanol', 'Dodecane', 'Nonanol',
       'Tetradecane', 'Glycerol', 'Trimethylpentane', 'H2S', 'Tm',
       'Hydroxyapatite', 'KTiOPO4', 'KTaO3', 'SnO2', 'KTiOAsO4', 'AgGaS2',
       'AgGaSe2', 'Pliolite S-5A', 'Allene', 'Difluoroethene',
       'Difluoroethane', 'Poly ether ether ketone', 'Graphite Oxide',
       'KCl', 'SmF3', 'NdF3', 'HoF3', 'GdF3',
       'Vinylchloride vinylacetate copolymer', 'Polysulfone', 'TaB2',
       'TiB2', 'TaB', 'UO2', 'Thiophene', 'Dimethyl sulfide',
       'Propylene sulfide', 'CS2', 'Trimethylene sulfide',
       'Ethylene sulfide', 'Dimethyl disulfide', 'CdTe', 'Propyne',
       'Butyne', 'bone', 'Octafluorocyclobutane', 'CBrF3',
       'Vinyl bromide', 'Bromoethane', 'Dibromotetrafluoroethane',
       'Hexafluoroethane', 'CClF3', 'CCl2F2', 'Ethyl iodide', 'CHCl2F',
       'SO2', 'Dimethyl sulfite', 'Trimethylamine', 'Dimethylamine',
       'Ethylamine', 'Methylamine', 'CR-39', 'NO', 'Vinyl chloride',
       'Fluoroform', 'Trifluoroethane', 'C2H3ClF2', 'C2H2ClF3', 'VO2',
       'Eurofer97', 'Mu metal', 'Permalloy', 'Teflon', 'AlF3', 'EP-PTCDI',
       'Celluloid', 'BaCl2', 'BaF2', 'WO3', 'NiSi', 'ZnSe'], dtype=object)

In [43]:
df_harmonized_dedx = harmonize_dedx_units(df_harmonized_energy, to="MeV/(mg/cm2)")
df_harmonized_dedx

Some rows were removed in harmonize_dedx_units because they contain non-elemental targets.

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,dataset_last_modification,publication_year,ref_id,citation_reference,doi,comments,ion_mass,target_mass,target_rho
0,Al,27.0,Ag,s,0.159000,MeV/u,4.369000,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682,10.503675
1,Al,27.0,Ag,s,0.308000,MeV/u,5.963000,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682,10.503675
2,Al,27.0,Ag,s,0.498000,MeV/u,6.802000,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682,10.503675
3,Al,27.0,Ag,s,0.727000,MeV/u,7.042000,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682,10.503675
4,Al,27.0,Ag,s,0.981000,MeV/u,7.099000,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682,10.503675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35380,He,4.0,Si,s,0.615609,MeV/u,0.950142,MeV/(mg/cm2),4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,28.0850,2.321034
35381,He,4.0,Si,s,0.643037,MeV/u,0.858366,MeV/(mg/cm2),4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,28.0850,2.321034
35382,He,4.0,Si,s,0.679608,MeV/u,0.885813,MeV/(mg/cm2),4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,28.0850,2.321034
35383,He,4.0,Si,s,0.706021,MeV/u,0.788676,MeV/(mg/cm2),4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,28.0850,2.321034
35384,He,4.0,Si,s,0.727354,MeV/u,0.794036,MeV/(mg/cm2),4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,28.0850,2.321034

In [44]:
projectiles = list(df_original["projectile_name"].unique())
targets = list(df_original["target_name"].unique())

print(f"number of projectiles: {len(projectiles)}")
print(f"number of targets: {len(targets)}")

unique_combinations = df_original[["projectile_name", "target_name"]].drop_duplicates()
print(f"number of unique combinations: {len(unique_combinations)}")
unique_combinations

number of projectiles: 58
number of targets: 275
number of unique combinations: 1532

      projectile_name target_name
0                  Al          Ag
13                 Al          Al
24                 Al          Cu
38                 Al      Carbon
44                 Al          Au
...               ...         ...
64017              Be       Ta2O5
64099              Li       Nb2O5
64123              Li       Ta2O5
64318              Be        ZrO2
64399              He        ZrO2

[1532 rows x 2 columns]

In [45]:
from ipywidgets import interact

df_elemental_only = df_harmonized_dedx[
    df_harmonized_dedx["target_name"].apply(is_element_in_periodic_table)
]

all(df_elemental_only == df_harmonized_dedx)

True

In [46]:
df_elemental_only["target_name"].unique()

array(['Ag', 'Al', 'Cu', 'C', 'Au', 'Ta', 'Si', 'Y', 'Nb', 'Co', 'Sn',
       'V', 'Mg', 'Fe', 'Ni', 'Ar', 'He', 'Pt', 'Be', 'Sc', 'Cr', 'Ti',
       'Mn', 'Ca', 'Zn', 'Zr', 'Gd', 'Xe', 'Kr', 'Ne', 'Te', 'Se', 'W',
       'Ge', 'Bi', 'Sb', 'Hf', 'Mo', 'Re', 'Pd', 'Cl', 'Br', 'Pb', 'Li',
       'U', 'Ir', 'In', 'Rb', 'Sr', 'Sm', 'Yb', 'Ho', 'Cd', 'Rh', 'Th',
       'Ru', 'Er', 'Lu', 'Ga', 'B', 'Pr', 'Ce', 'La', 'Dy', 'Cs', 'Tb',
       'Nd', 'Tm'], dtype=object)

In [ ]:
df = df_elemental_only.sort_values(["projectile_name"])
projectiles = list(df_elemental_only["projectile_name"].unique())


def filter_by_ion(ion: str):
    df_ = df.copy()

    df_ = df_[df_["projectile_name"] == ion]

    fig = px.scatter(
        df_,
        x="energy",
        y="stopping_power",
        symbol="stopping_unit",
        color="target_name",
        log_x=True,
        log_y=True,
        hover_data=["energy", "energy_unit", "stopping_unit"],
        width=1200,
        height=600,
    )
    # fig.show()
    return fig


f = interact(filter_by_ion, ion=projectiles)

interactive(children=(Dropdown(description='ion', options=('Al', 'C', 'O', 'Ag', 'Ti', 'Cu', 'Au', 'I', 'N', '…

In [52]:
df = df.sort_values(["target_name"])
targets = df["target_name"].unique()


def filter_by_target(target: str):
    df_ = df.copy()

    df_ = df_[df_["target_name"] == target]

    fig = px.scatter(
        df_,
        x="energy",
        y="stopping_power",
        color="projectile_name",
        symbol="stopping_unit",
        log_x=True,
        log_y=True,
        hover_data=["energy", "energy_unit", "stopping_unit"],
        width=1200,
        height=600,
    )

    fig.show()


selected_ion = interact(filter_by_target, target=targets)

interactive(children=(Dropdown(description='target', options=('Ag', 'Al', 'Ar', 'Au', 'B', 'Be', 'Bi', 'Br', '…

In [49]:
df_elemental_only

,projectile_name,ion_isotope,target_name,phase,energy,energy_unit,stopping_power,stopping_unit,percentage_error,target_mass_atom_ratio,dataset_last_modification,publication_year,ref_id,citation_reference,doi,comments,ion_mass,target_mass,target_rho
0,Al,27.0,Ag,s,0.159000,MeV/u,4.369000,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682,10.503675
1,Al,27.0,Ag,s,0.308000,MeV/u,5.963000,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682,10.503675
2,Al,27.0,Ag,s,0.498000,MeV/u,6.802000,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682,10.503675
3,Al,27.0,Ag,s,0.727000,MeV/u,7.042000,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682,10.503675
4,Al,27.0,Ag,s,0.981000,MeV/u,7.099000,MeV/(mg/cm2),5,107.8682,2023-11-27,1991,Ab1991a,"M.Abdesselam,J.P.Stoquert,G.Guillaume,M.Hage-A...",10.1016/0168-583x(91)95310-a,NaN,26.981538,107.8682,10.503675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35380,He,4.0,Si,s,0.615609,MeV/u,0.950142,MeV/(mg/cm2),4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,28.0850,2.321034
35381,He,4.0,Si,s,0.643037,MeV/u,0.858366,MeV/(mg/cm2),4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,28.0850,2.321034
35382,He,4.0,Si,s,0.679608,MeV/u,0.885813,MeV/(mg/cm2),4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,28.0850,2.321034
35383,He,4.0,Si,s,0.706021,MeV/u,0.788676,MeV/(mg/cm2),4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,28.0850,2.321034
35384,He,4.0,Si,s,0.727354,MeV/u,0.794036,MeV/(mg/cm2),4,28.0850,2023-11-27,2007,ZJ2007,"Y.Zhang,J.Jensen,G.Possnert,D.A.Grove,In-Tae B...",10.1016/j.nimb.2007.04.276,NaN,4.002603,28.0850,2.321034

In [ ]:
# check density values
density = df_elemental_only["target_name"].apply(get_element_density)
tabulated_density = df_elemental_only["target_rho"]

px.scatter(x=tabulated_density, y=density, labels={"x": "tabulated density", "y": "calculated density"})